package com.wqy.campusbbs.model;

public class Specialty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALTY.ID
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALTY.NAME
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALTY.GMT_CREATE
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALTY.ID
     *
     * @return the value of SPECIALTY.ID
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALTY.ID
     *
     * @param id the value for SPECIALTY.ID
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALTY.NAME
     *
     * @return the value of SPECIALTY.NAME
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALTY.NAME
     *
     * @param name the value for SPECIALTY.NAME
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALTY.GMT_CREATE
     *
     * @return the value of SPECIALTY.GMT_CREATE
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALTY.GMT_CREATE
     *
     * @param gmtCreate the value for SPECIALTY.GMT_CREATE
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}