package com.wqy.campusbbs.mapper;

import com.wqy.campusbbs.model.Specialty;
import com.wqy.campusbbs.model.SpecialtyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SpecialtyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    long countByExample(SpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int deleteByExample(SpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int insert(Specialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int insertSelective(Specialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    List<Specialty> selectByExampleWithRowbounds(SpecialtyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    List<Specialty> selectByExample(SpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    Specialty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") Specialty record, @Param("example") SpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByExample(@Param("record") Specialty record, @Param("example") SpecialtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByPrimaryKeySelective(Specialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALTY
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByPrimaryKey(Specialty record);
}
