package com.wqy.campusbbs.mapper;

import com.wqy.campusbbs.model.StudentClass;
import com.wqy.campusbbs.model.StudentClassExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface StudentClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    long countByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int deleteByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int insert(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int insertSelective(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    List<StudentClass> selectByExampleWithRowbounds(StudentClassExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    List<StudentClass> selectByExample(StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    StudentClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") StudentClass record, @Param("example") StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByExample(@Param("record") StudentClass record, @Param("example") StudentClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByPrimaryKeySelective(StudentClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENT_CLASS
     *
     * @mbg.generated Fri Apr 16 18:30:08 CST 2021
     */
    int updateByPrimaryKey(StudentClass record);
}
